export interface Player {
  "36": string;
  "37": string;
  name: string;
  Village_name: string;
  Kingdom_name: string;
  actions_remaining: string;
  "VIP time": string;
  "QOL time": string;
  lvl: string;
  "Target Enchant": string;
  G1_LH_enchant_boost: string;
  G2_RH_enchant_boost: string;
  G3_Head_enchant_boost: string;
  G4_Chest_enchant_boost: string;
  G5_Hands_enchant_boost: string;
  G6_Legs_enchant_boost: string;
  G7_Feet_enchant_boost: string;
  "Stat Strength": string;
  "Stat Health": string;
  "Stat Agility": string;
  "Stat Dexterity": string;
  "Sum Stats": string;
  "Dungeon lvl": string;
  Decorations: string;
  "HS Mine": string;
  "HS Farm": string;
  "HS Logging": string;
  "HS Fishing": string;
  "House Chair": string;
  "House Stove": string;
  "House Sink": string;
  "House Basket": string;
  "House Barrel": string;
  "Gold gained": string;
  "Relics gained": string;
  "Res gained": string;
  "Total income": string;
  "Production Ratios": string;
  Score: string;
  "Diff scores": null | string;
  "count scores": null | string;
  "cummulative count": null | string;
}
